twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  api-key: ${TWILIO_API_KEY}
  api-secret: ${TWILIO_API_SECRET}

minio:
  url: ${MINIO_URL}
  access:
    key: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_ACCESS_SECRET}
